<?php
namespace frontend\widgets;

use backend\models\GoodsCategory;
use yii\base\Widget;

class GoodscategoryWidget extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
    $models =GoodsCategory::findAll(['parent_id'=>'id']);
    $goodscategoty_html =
        $this->renderFile('@app/widgets/view/goodscategory.php',['models'=>$models]);
    return $goodscategoty_html;
    }
}